"""
plot_score.py

Load the CSV with test metrics for all epochs and:
  - print the best epoch for several metrics (F1, CSI, loss, precision, recall, accuracy)
  - save plots of loss vs epoch and F1/CSI vs epoch.

Adapted from transformer_cnn_model/plot_score.py for st-Swin-UNet.

By default, the script:
  - reads the metrics CSV path from `eval_cfg.scores_csv`
  - saves plots into `data_cfg.plots_dir`
  - uses model variant and temporal aggregation for labels.

The CSV is expected to be generated by `eval_all_checkpoints.py` and to contain
(at least) the following columns:
    epoch, test_loss, test_acc, test_prec, test_rec, test_f1, test_csi

Usage example (from repo root)
------------------------------
    conda activate braided

    # Plot for tiny variant (default)
    python -m swin-unet.plot_score

    # Plot for small variant
    python -m swin-unet.plot_score --variant small

    # Use custom CSV path
    python -m swin-unet.plot_score --csv-path swin-unet/scores/custom_metrics.csv

Outputs
-------
  - Console printout of:
        * best epoch by test_f1
        * best epoch by test_csi
        * best epoch by lowest test_loss
        * best epoch by test_prec
        * best epoch by test_rec
        * best epoch by test_acc

  - CSV summary of best epochs:
        data_cfg.plots_dir / "best_epoch_summary_stswin_{variant}.csv"

  - Plots:
        data_cfg.plots_dir / "test_loss_stswin_{variant}.png"
        data_cfg.plots_dir / "test_f1_csi_stswin_{variant}.png"
"""

import argparse
import sys
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt

# Add swin-unet directory to path
sys.path.insert(0, str(Path(__file__).parent))
from config import data_cfg, eval_cfg, model_cfg


def parse_args():
    parser = argparse.ArgumentParser(
        description="Plot test metrics from CSV and identify best epochs."
    )
    parser.add_argument(
        "--variant",
        type=str,
        default=model_cfg.variant,
        choices=["tiny", "small"],
        help=f"Model variant to plot (default: {model_cfg.variant})",
    )
    parser.add_argument(
        "--csv-path",
        type=str,
        default=None,
        help="Path to metrics CSV file (default: auto-generated based on variant)",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=str(data_cfg.plots_dir),
        help=f"Directory to save plots (default: {data_cfg.plots_dir})",
    )
    return parser.parse_args()


# Parse arguments
args = parse_args()

# Update eval config for the specified variant
eval_cfg.update_for_variant(args.variant)

# Path to CSV with metrics for all epochs
csv_path = args.csv_path if args.csv_path else eval_cfg.scores_csv

# Directory where plots will be saved
plots_dir = Path(args.output_dir)
plots_dir.mkdir(parents=True, exist_ok=True)

# Model identifier for titles / filenames
model_name = f"stswin_{args.variant}"  # e.g. "stswin_tiny" or "stswin_small"

# Load metrics
print(f"Loading metrics from {csv_path}")
df = pd.read_csv(csv_path)
print(f"Loaded {len(df)} epochs of data\n")

# --------------------------------------------------------------------
# Helper function to print best row for any metric
# --------------------------------------------------------------------
def print_best(df, metric, higher_is_better=True):
    if higher_is_better:
        idx = df[metric].idxmax()
    else:
        idx = df[metric].idxmin()

    row = df.loc[idx]
    print(
        f"Best {metric} : epoch {int(row['epoch'])} "
        f"({metric} = {row[metric]:.6f}, "
        f"loss = {row['test_loss']:.6f}, "
        f"F1 = {row['test_f1']:.4f}, "
        f"CSI = {row['test_csi']:.4f}, "
        f"prec = {row['test_prec']:.4f}, "
        f"rec = {row['test_rec']:.4f}, "
        f"acc = {row['test_acc']:.4f})"
    )
    return row


print("==================== BEST EPOCHS ====================")

# Highest F1
best_f1 = print_best(df, "test_f1")

# Highest CSI
best_csi = print_best(df, "test_csi")

# Lowest loss
best_loss = print_best(df, "test_loss", higher_is_better=False)

# Highest precision
best_prec = print_best(df, "test_prec")

# Highest recall
best_rec = print_best(df, "test_rec")

# Highest accuracy
best_acc = print_best(df, "test_acc")

print("=====================================================\n")

# Optional summary table
summary_df = pd.DataFrame({
    "metric": ["F1", "CSI", "Loss", "Precision", "Recall", "Accuracy"],
    "epoch": [
        int(best_f1["epoch"]),
        int(best_csi["epoch"]),
        int(best_loss["epoch"]),
        int(best_prec["epoch"]),
        int(best_rec["epoch"]),
        int(best_acc["epoch"]),
    ],
    "value": [
        best_f1["test_f1"],
        best_csi["test_csi"],
        best_loss["test_loss"],
        best_prec["test_prec"],
        best_rec["test_rec"],
        best_acc["test_acc"],
    ]
})
summary_path = plots_dir / f"best_epoch_summary_{model_name}.csv"
summary_df.to_csv(summary_path, index=False)
print(f"Saved summary of best epochs to {summary_path}")

# --------------------------------------------------------------------
# Plot test loss vs epoch
# --------------------------------------------------------------------
fig_loss = plt.figure(figsize=(10, 6))
plt.plot(df["epoch"], df["test_loss"], marker="o", linewidth=2, markersize=6)
plt.xlabel("Epoch", fontsize=12)
plt.ylabel("Test Loss", fontsize=12)
plt.title(f"Test Loss vs Epoch (st-Swin-UNet {args.variant})", fontsize=14, fontweight="bold")
plt.grid(True, alpha=0.3)

loss_plot_path = plots_dir / f"test_loss_{model_name}.png"
fig_loss.savefig(loss_plot_path, dpi=300, bbox_inches="tight")
print(f"Saved loss plot to {loss_plot_path}")

# --------------------------------------------------------------------
# Plot F1 and CSI vs epoch
# --------------------------------------------------------------------
fig_scores = plt.figure(figsize=(10, 6))
plt.plot(df["epoch"], df["test_f1"], marker="o", linewidth=2, markersize=6, label="F1")
plt.plot(df["epoch"], df["test_csi"], marker="s", linewidth=2, markersize=6, label="CSI")
plt.xlabel("Epoch", fontsize=12)
plt.ylabel("Score", fontsize=12)
plt.title(f"F1 and CSI vs Epoch (st-Swin-UNet {args.variant})", fontsize=14, fontweight="bold")
plt.legend(fontsize=11)
plt.grid(True, alpha=0.3)

scores_plot_path = plots_dir / f"test_f1_csi_{model_name}.png"
fig_scores.savefig(scores_plot_path, dpi=300, bbox_inches="tight")
print(f"Saved F1/CSI plot to {scores_plot_path}")

print("\nDone! Close the plot windows to exit.")
plt.show()
